### ISSUE TITLE
Instruct node-gyp to use specific version of g++ and gcc 

### ISSUE THREAD

**Issue by easwaraa** [kentonv/node-capnp#26]
Hello,

I am new to the world of installing Javascript modules and I am having the task of installing capnp JS libraries using g++ v4.8 in our RHEL6 environment. 

As we only have v4.4.7 in /usr/bin/g++, we decided to use the g++ (v4.8.2) installed in /opt. 

I downloaded the source from  https://github.com/kentonv/node-capnp and added the below lines to binding.gyp but it doesn’t work.

'make_global_settings': [
    {  
      'CXX': ['/opt/rh/devtoolset-2/root/usr/bin/g++'],
      'CC': ['/opt/rh/devtoolset-2/root/usr/bin/gcc']
    }],

When I straced the process, found that node-gyp is looking for the g++ libraries only in below location. 

/usr/lib/node_modules/npm/bin/node-gyp-bin
/u/easwaraa/node_modules/capnp/node_modules/.bin
/usr/bin

I tried searching around to see if I can update the path somewhere but couldn’t find it.  FWIW, I tried updating my .pathrc too but it didn’t help.

When I run npm install, I get the below message.

 ~/tmp/capnproto/temp_js_RPC/node-capnp $ npm install

> capnp@0.1.11 install /u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp
> node ./build.js

make: Entering directory `/u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp/build'
  CXX(target) Release/obj.target/capnp/src/node-capnp/capnp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [Release/obj.target/capnp/src/node-capnp/capnp.o] Error 1
make: Leaving directory `/u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-573.8.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
Build failed
npm ERR! weird error 1
npm ERR! not ok code 0

How can I update node-gyp to use the different version of g++?

Please let me know if something isn’t clear.

**Comment by kentonv** [comment]
Unfortunately, I do not actually know the answer to your question! I don't really know much about node-gyp myself.

The "standard" (if there is one) way to tell a build system what compiler to use is via the `CXX` environment variable. So I would suggest trying `export CXX=g++-4.8` (or whatever command you use to run G++ 4.8) before running npm. If that doesn't work, I guess you'll have to ask the npm people what to try next. :/

**Comment by easwaraa** [comment]
Thanks for the response :).

Setting the env variable fixed this issue but still node gyp rebuild is failing.

~/tmp/capnproto/temp_js_RPC/node-capnp $ env CC=/opt/rh/devtoolset-2/root/usr/bin/gcc CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ V=1 npm install

> capnp@0.1.11 install /u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp
> node ./build.js

make: Entering directory `/u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp/build'
  /opt/rh/devtoolset-2/root/usr/bin/g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/usr/include -I/usr/include/node -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer  -std=c++11  -MMD -MF ./Release/.deps/Release/obj.target/capnp/src/node-capnp/capnp.o.d.raw  -c -o Release/obj.target/capnp/src/node-capnp/capnp.o ../src/node-capnp/capnp.cc
../src/node-capnp/capnp.cc: In member function \u2018capnp::Orphan<capnp::DynamicValue> v8capnp::{anonymous}::FromJsConverter::orphanFromJs(capnp::StructSchema::Field, capnp::Orphanage, capnp::Type, v8::Handle<v8::Value>)\u2019:
../src/node-capnp/capnp.cc:1351:18: error: \u2018class capnp::Type\u2019 has no member named \u2018whichAnyPointerKind\u2019
         if (type.whichAnyPointerKind() == capnp::schema::Type::AnyPointer::Unconstrained::CAPABILITY) {
                  ^
../src/node-capnp/capnp.cc:1351:76: error: \u2018capnp::schema::Type::AnyPointer::Unconstrained\u2019 has not been declared
         if (type.whichAnyPointerKind() == capnp::schema::Type::AnyPointer::Unconstrained::CAPABILITY) {
                                                                            ^
../src/node-capnp/capnp.cc:1354:68: error: no matching function for call to \u2018capnp::DynamicCapability::Client::Client(capnp::Capability::Client)\u2019
             capnp::DynamicCapability::Client dynamicCap(kj::mv(cap));
                                                                    ^
../src/node-capnp/capnp.cc:1354:68: note: candidates are:
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:480:10: note: template<class T> capnp::DynamicCapability::Client::Client(capnp::InterfaceSchema, kj::Own<T>&&)
   inline Client(InterfaceSchema schema, kj::Own<T>&& server);
          ^
/usr/include/capnp/dynamic.h:480:10: note:   template argument deduction/substitution failed:
../src/node-capnp/capnp.cc:1354:68: note:   cannot convert \u2018kj::mv<capnp::Capability::Client>((* & cap))\u2019 (type \u2018capnp::Capability::Client\u2019) to type \u2018capnp::InterfaceSchema\u2019
             capnp::DynamicCapability::Client dynamicCap(kj::mv(cap));
                                                                    ^
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:476:3: note: capnp::DynamicCapability::Client::Client(capnp::InterfaceSchema, kj::Own<capnp::ClientHook>&&)
   Client(InterfaceSchema schema, kj::Own<ClientHook>&& hook)
   ^
/usr/include/capnp/dynamic.h:476:3: note:   candidate expects 2 arguments, 1 provided
/usr/include/capnp/dynamic.h:455:10: note: template<class T, class> capnp::DynamicCapability::Client::Client(kj::Own<T>&&)
   inline Client(kj::Own<T>&& server);
          ^
/usr/include/capnp/dynamic.h:455:10: note:   template argument deduction/substitution failed:
../src/node-capnp/capnp.cc:1354:68: note:   \u2018capnp::Capability::Client\u2019 is not derived from \u2018kj::Own<T>\u2019
             capnp::DynamicCapability::Client dynamicCap(kj::mv(cap));
                                                                    ^
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:452:10: note: template<class T, class> capnp::DynamicCapability::Client::Client(T&&)
   inline Client(T&& client);
          ^
/usr/include/capnp/dynamic.h:452:10: note:   template argument deduction/substitution failed:
In file included from /usr/include/capnp/layout.h:38:0,
                 from /usr/include/capnp/generated-header-support.h:31,
                 from /usr/include/capnp/schema.capnp.h:7,
                 from /usr/include/capnp/schema.h:33,
                 from /usr/include/capnp/dynamic.h:40,
                 from ../src/node-capnp/capnp.cc:31:
/usr/include/capnp/any.h:259:51: error: no type named \u2018Calls\u2019 in \u2018kj::Decay_<capnp::Capability::Client>::Type {aka class capnp::Capability::Client}\u2019
     template <typename T, typename = kj::EnableIf<CAPNP_KIND(FromClient<T>) == Kind::INTERFACE>>
                                                   ^
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:449:3: note: capnp::DynamicCapability::Client::Client()
   Client() = default;
   ^
/usr/include/capnp/dynamic.h:449:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/capnp/dynamic.h:444:26: note: capnp::DynamicCapability::Client::Client(capnp::DynamicCapability::Client&)
 class DynamicCapability::Client: public Capability::Client {
                          ^
/usr/include/capnp/dynamic.h:444:26: note:   no known conversion for argument 1 from \u2018capnp::Capability::Client\u2019 to \u2018capnp::DynamicCapability::Client&\u2019
/usr/include/capnp/dynamic.h:444:26: note: capnp::DynamicCapability::Client::Client(capnp::DynamicCapability::Client&&)
/usr/include/capnp/dynamic.h:444:26: note:   no known conversion for argument 1 from \u2018capnp::Capability::Client\u2019 to \u2018capnp::DynamicCapability::Client&&\u2019
../src/node-capnp/capnp.cc: In function \u2018v8::Handle<v8::Value> v8capnp::{anonymous}::valueToJs(v8capnp::{anonymous}::CapnpContext&, capnp::DynamicValue::Reader, capnp::Type, v8::Handle<v8::Value>)\u2019:
../src/node-capnp/capnp.cc:1598:16: error: \u2018class capnp::Type\u2019 has no member named \u2018whichAnyPointerKind\u2019
       if (type.whichAnyPointerKind() == capnp::schema::Type::AnyPointer::Unconstrained::CAPABILITY) {
                ^
../src/node-capnp/capnp.cc:1598:74: error: \u2018capnp::schema::Type::AnyPointer::Unconstrained\u2019 has not been declared
       if (type.whichAnyPointerKind() == capnp::schema::Type::AnyPointer::Unconstrained::CAPABILITY) {
                                                                          ^
../src/node-capnp/capnp.cc:1601:64: error: no matching function for call to \u2018capnp::DynamicCapability::Client::Client(capnp::Capability::Client)\u2019
         capnp::DynamicCapability::Client dynamicCap(kj::mv(cap));
                                                                ^
../src/node-capnp/capnp.cc:1601:64: note: candidates are:
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:480:10: note: template<class T> capnp::DynamicCapability::Client::Client(capnp::InterfaceSchema, kj::Own<T>&&)
   inline Client(InterfaceSchema schema, kj::Own<T>&& server);
          ^
/usr/include/capnp/dynamic.h:480:10: note:   template argument deduction/substitution failed:
../src/node-capnp/capnp.cc:1601:64: note:   cannot convert \u2018kj::mv<capnp::Capability::Client>((* & cap))\u2019 (type \u2018capnp::Capability::Client\u2019) to type \u2018capnp::InterfaceSchema\u2019
         capnp::DynamicCapability::Client dynamicCap(kj::mv(cap));
                                                                ^
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:476:3: note: capnp::DynamicCapability::Client::Client(capnp::InterfaceSchema, kj::Own<capnp::ClientHook>&&)
   Client(InterfaceSchema schema, kj::Own<ClientHook>&& hook)
   ^
/usr/include/capnp/dynamic.h:476:3: note:   candidate expects 2 arguments, 1 provided
/usr/include/capnp/dynamic.h:455:10: note: template<class T, class> capnp::DynamicCapability::Client::Client(kj::Own<T>&&)
   inline Client(kj::Own<T>&& server);
          ^
/usr/include/capnp/dynamic.h:455:10: note:   template argument deduction/substitution failed:
../src/node-capnp/capnp.cc:1601:64: note:   \u2018capnp::Capability::Client\u2019 is not derived from \u2018kj::Own<T>\u2019
         capnp::DynamicCapability::Client dynamicCap(kj::mv(cap));
                                                                ^
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:452:10: note: template<class T, class> capnp::DynamicCapability::Client::Client(T&&)
   inline Client(T&& client);
          ^
/usr/include/capnp/dynamic.h:452:10: note:   template argument deduction/substitution failed:
In file included from /usr/include/capnp/layout.h:38:0,
                 from /usr/include/capnp/generated-header-support.h:31,
                 from /usr/include/capnp/schema.capnp.h:7,
                 from /usr/include/capnp/schema.h:33,
                 from /usr/include/capnp/dynamic.h:40,
                 from ../src/node-capnp/capnp.cc:31:
/usr/include/capnp/any.h:259:51: error: no type named \u2018Calls\u2019 in \u2018kj::Decay_<capnp::Capability::Client>::Type {aka class capnp::Capability::Client}\u2019
     template <typename T, typename = kj::EnableIf<CAPNP_KIND(FromClient<T>) == Kind::INTERFACE>>
                                                   ^
In file included from ../src/node-capnp/capnp.cc:31:0:
/usr/include/capnp/dynamic.h:449:3: note: capnp::DynamicCapability::Client::Client()
   Client() = default;
   ^
/usr/include/capnp/dynamic.h:449:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/capnp/dynamic.h:444:26: note: capnp::DynamicCapability::Client::Client(capnp::DynamicCapability::Client&)
 class DynamicCapability::Client: public Capability::Client {
                          ^
/usr/include/capnp/dynamic.h:444:26: note:   no known conversion for argument 1 from \u2018capnp::Capability::Client\u2019 to \u2018capnp::DynamicCapability::Client&\u2019
/usr/include/capnp/dynamic.h:444:26: note: capnp::DynamicCapability::Client::Client(capnp::DynamicCapability::Client&&)
/usr/include/capnp/dynamic.h:444:26: note:   no known conversion for argument 1 from \u2018capnp::Capability::Client\u2019 to \u2018capnp::DynamicCapability::Client&&\u2019
../src/node-capnp/capnp.cc: In member function \u2018capnp::Capability::Client v8capnp::{anonymous}::RpcConnection::import(kj::StringPtr)\u2019:
../src/node-capnp/capnp.cc:1761:46: warning: \u2018capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatId; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]\u2019 is deprecated (declared at /usr/include/capnp/rpc.h:366) [-Wdeprecated-declarations]
     return rpcSystem.restore(hostId, objectId);
                                              ^
../src/node-capnp/capnp.cc: In function \u2018v8::Handle<v8::Value> v8capnp::{anonymous}::fulfillPromisedCap(const v8::Arguments&)\u2019:
../src/node-capnp/capnp.cc:2253:29: warning: unused variable \u2018context\u2019 [-Wunused-variable]
   KJV8_UNWRAP(CapnpContext, context, args.Data());
                             ^
../src/node-capnp/capnp.cc:875:9: note: in definition of macro \u2018KJV8_UNWRAP\u2019
   type& name = KJ_ASSERT_NONNULL(name##_maybe)
         ^
../src/node-capnp/capnp.cc: In function \u2018v8::Handle<v8::Value> v8capnp::{anonymous}::rejectPromisedCap(const v8::Arguments&)\u2019:
../src/node-capnp/capnp.cc:2268:29: warning: unused variable \u2018context\u2019 [-Wunused-variable]
   KJV8_UNWRAP(CapnpContext, context, args.Data());
                             ^
../src/node-capnp/capnp.cc:875:9: note: in definition of macro \u2018KJV8_UNWRAP\u2019
   type& name = KJ_ASSERT_NONNULL(name##_maybe)
         ^
make: *** [Release/obj.target/capnp/src/node-capnp/capnp.o] Error 1
make: Leaving directory `/u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-573.8.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/easwaraa/tmp/capnproto/temp_js_RPC/node-capnp
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
Build failed
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by kentonv** [comment]
I think this is because of version skew.

If you're using node-capnp from git, you need to use Cap'n Proto C++ from git. If you are using the release version of Cap'n Proto (0.5.x), then you'll need to install the release version of node-capnp from npm, or git checkout the corresponding commit, which I think is this: https://github.com/kentonv/node-capnp/commit/dc538dd4ce390a2615bd645f782c381033632123

Sorry that this is a bit of a mess.

**Comment by easwaraa** [comment]
Thanks for the suggestion. The fix was spot on. 

I ran ‘env CC=/opt/rh/devtoolset-2/root/usr/bin/gcc CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ npm install capnp’ and it seems to have installed the required node_modules.

~ $ env CC=/opt/rh/devtoolset-2/root/usr/bin/gcc CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ npm install capnp
npm http GET https://registry.npmjs.org/capnp
npm http 304 https://registry.npmjs.org/capnp

> capnp@0.1.11 install /u/easwaraa/node_modules/capnp
> node ./build.js

make: Entering directory `/u/easwaraa/node_modules/capnp/build'
  CXX(target) Release/obj.target/capnp/src/node-capnp/capnp.o
../src/node-capnp/capnp.cc: In member function \u2018capnp::Capability::Client v8capnp::{anonymous}::RpcConnection::import(kj::StringPtr)\u2019:
../src/node-capnp/capnp.cc:1732:46: warning: \u2018capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatId; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]\u2019 is deprecated (declared at /usr/include/capnp/rpc.h:366) [-Wdeprecated-declarations]
     return rpcSystem.restore(hostId, objectId);
                                              ^
../src/node-capnp/capnp.cc: In function \u2018v8::Handle<v8::Value> v8capnp::{anonymous}::fulfillPromisedCap(const v8::Arguments&)\u2019:
../src/node-capnp/capnp.cc:2232:29: warning: unused variable \u2018context\u2019 [-Wunused-variable]
   KJV8_UNWRAP(CapnpContext, context, args.Data());
                             ^
../src/node-capnp/capnp.cc:858:9: note: in definition of macro \u2018KJV8_UNWRAP\u2019
   type& name = KJ_ASSERT_NONNULL(name##_maybe)
         ^
../src/node-capnp/capnp.cc: In function \u2018v8::Handle<v8::Value> v8capnp::{anonymous}::rejectPromisedCap(const v8::Arguments&)\u2019:
../src/node-capnp/capnp.cc:2247:29: warning: unused variable \u2018context\u2019 [-Wunused-variable]
   KJV8_UNWRAP(CapnpContext, context, args.Data());
                             ^
../src/node-capnp/capnp.cc:858:9: note: in definition of macro \u2018KJV8_UNWRAP\u2019
   type& name = KJ_ASSERT_NONNULL(name##_maybe)
         ^
  SOLINK_MODULE(target) Release/obj.target/capnp.node
  SOLINK_MODULE(target) Release/obj.target/capnp.node: Finished
  COPY Release/capnp.node
make: Leaving directory `/u/easwaraa/node_modules/capnp/build'
Installed in `/u/easwaraa/node_modules/capnp/bin/linux-x64-v8-3.14/capnp.node`
capnp@0.1.11 node_modules/capnp

~/node_modules/capnp $ ls
CONTRIBUTORS  LICENSE  README.md  bin  binding.gyp  build  build.js  package.json  src

I was under the impression that there will be a .js file which will be present. Am I missing something here? Is it fine to run the above command with -g so that the modules gets installed in /usr/lib/node_modules?

**Comment by kentonv** [comment]
Node will search for modules in all directories called `node_modules` in any parent of the working directory. But installing globally is also an option (you'll need to be root, of course).

Either way, you use the module by doing `require("capnp")` -- you shouldn't be trying to import specific JS files from within it.

**Comment by easwaraa** [comment]
Lemme try this and get back to you. Thanks :).

**Comment by easwaraa** [comment]
Thanks, it worked as expected.

~/tmp/capnproto $ cat first.js 
console.log("Hello, World!")
var abc = require("capnp");
console.log(abc);
~/tmp/capnproto $ 

~/tmp/capnproto $ node first.js 
Hello, World!
{ import: [Function],
  importSystem: [Function],
  connect: [Function],
  parse: [Function],
  serialize: [Function],
  Capability: [Function: Capability],
  bytesToPreorder: [Function] }
~/tmp/capnproto $

**Comment by kentonv** [comment]
OK, closing since I don't think we found anything that needs changing in node-capnp. Let me know if I missed something.
